knl/niv-updater-action

niv-updater
'hub pull-request' requires a local checkout, so a run would fail in case there was
no preceeding checkout step in the workflow.
Switch to using an API call, which doesn't have the said limitation.
What a dumb mistake.
Closes #1.
=> fix: Use 'hub api' to create the update branch

README.adoc, action.yml, niv-updater
Unlike other lists, we can't split on `,` for the labels, as they can contain
anything on GitHub, even emojis 🤢  Thus, we need to split on a newline, the
only character that a label can't contain. This, in turn, makes the code
unbelieveably simpler, since bash assumes everything to be split on a newline
🎉
In order to properly send the data to GitHub's API, we need to rely on `jo`, as
manually constructing JSON payloads is for optimists.
Closes #5.
=> Add labels

niv-updater
GitHub used #123 as a shorthand for a URL to the issue **in the same
repository**. Thus, when constructing the changelogs, all #123 in the changelog
would render as a link to the repository where niv-updater-action operates,
instead of pointing to the depdendency's repository.
To fix this issue, prepend anything that looks like #<numbers> with the name of
the dependency (owner/repository).
Closes #8.
=> Emit correct links to issues and PRs in the changelog

README.adoc, action.yml, niv-updater
Most of the time these merge commit carry no information. Add the option to skip
them, and make it a sane default.
Closes #6.
=> Add an option to skip showing merges in the changelogs

README.adoc, action.yml, niv-updater
Hopefully, this will be helpful for someone.
Closes #7.
=> Allow custom prefix/suffix for commit descriptions

niv-updater
Fail early in case the action receives a wrong GITHUB_TOKEN, that is, one that
is invalid. This doesn't cover the case where the token doesn't have sufficient
rights, as that will be discovered later.
Closes #15
=> Check GITHUB_TOKEN

niv-updater
git commit messages start with the subject, followed by an empty line and the body
of the commit. Due to old refactoring, the generated commit messages lost the
subject line, as that was now in the title, that is a separate file, used to set
the title of the PR. This change stores the commit message in a separate file
and generates it following the convention.
Closes #16
=> Fix generated commit message

README.adoc, action.yml, niv-updater
Have a prefix to the commit title itself, for example, to support conventional commits.
=> Add a title prefix support

niv-updater
This will speed up the execution a bit.
- `hub` is provided by the base image
- `jo`'s use has been replaced by `jq` -- `jq` is already used pervasively.
=> Do not install hub and jo via Nix

.github/issue_template.md, .github/workflows/issue-notifier.yml
Since GitHub doesn't have a good system for such a critical feature, make one.
This relies on two features:
- issue template will assign a label and make me the assignee for the issue
- if the latter doesn't cause a notification by email, the label will trigger issue-notifier action to send me an email via sendgrid
I really hate when I open an issue and I don't hear back. I don't want others to suffer with the same in my repositories.
=> Notify owners on new issue creation

niv-updater
Fix improperly created commit message (an empty line was not present between the title and the body).
Remove an empty space at the beginning of the title, when no title prefix is provided.
=> Fix whitespace/newline issues

README.adoc, action.yml, niv-updater
Closes #26
niv-update-action changelog in a GitHub PR contains references (in the form
of `owner/repo#PR_number`), which GitHub nicely turns into links.
However, what GitHub also does is it creates a backreference in those
PRs back to the PR created by niv-update-action. This pollutes the
upstream projects. Thus, this change adds an option to use a redirector
service in order to still have links, but avoid having backreferences.
=> Add option to avoid GitHub backreferencing the PR

niv-updater
If the changelog contains anyones username (@ + username), GitHub will dutifully notify that person that they have been mentioned. This is not nice for our generated changelogs, as it spams people and brings no value (the mention is not intentional). To retain the display, yet avoid notification, we print '@' followed by an UNICODE WORD JOINER character (that has zero width, but prevents splitting at this boundary), followed by the username.
=> Reformat mentions to reduce spamming of mentioned developers

niv-updater
Recent [changes in niv](https://github.com/nmattia/niv/pull/268) dropped
the usage of `ref` as a branch in git sources. The new attribute name is
`branch`.
=> Rename ref attribute to branch

README.adoc, action.yml, niv-updater
This avoids problems where newer versions of niv may break workflows,
due to backwards incompatible changes, or just bugs.
By default, we track master, which was the current behavior. However,
one may want to pin to a particular version of niv, because niv+Nix are
all about pinning.
Closes #4
=> Make niv version configurable

README.adoc, action.yml, niv-updater
Enabling `debug_output` will run the updater script under `set -x`,
effectively printing out any command that is to be executed. This can
help with reproducing the issues locally or plain old debugging.
Closes #34.
=> Add option for debug logs

niv-updater
The original code relied on `hub pr` which requires a local git checkout. That
might not work if niv-updater-action is used without previous checkout (a
completely legitimate use case).
This change switches to using GraphQL query to GitHub, that fetches the PR
number based on the branch name.
Fixes #38
=> Fix: Get PR number via GraphQL

niv-updater
When updating PRs, the code was taking just the commit message for the
new commit, instead of the combined title + message. This change fixes
it.
=> Fix commit message when PRs are updated

niv-updater
As these links come in many forms:
- `git+ssh://git@github.com/foo/bar`
- `ssh://git@github.com:foo/bar.git`
- `git@github.com:foo/bar.git`
This change takes care of properly handling each of them, so we could cover all
possible instances.
The code assumes that the content of `sources.json` is correct, and that `niv`
already verified that links are good. Thus, the checks and extractions are more
lenient than they should be.
Fixes #40
=> Better handling of GitHub SSH links

action.yml, niv-updater
Since GitHub switched to using `main` as the main branch (it used to be
`master`), update this action to support such case.
Also, in case there is a problem getting SHA for the branch, report an error
instead of silently dying.
=> Handle pull base other than master

niv-updater
Closes #45 
This ensures that we pull dependencies from niv's upstream cache as well, `cache.nixos.org`. Otherwise the action may spend hours rebuilding niv (ok, not niv itself, but dependencies).
NOTE: would be good to suggest to users that they set a [`timeout-minutes`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) of O(1minute) to avoid hours of actions time being wasted rebuilding the world!
NOTE2: unfortunately we can't set `--max-jobs` to 0 because `nix-env` is trying to build something (most likely the user profile). I guess you could do a `nix-build --max-jobs 0` followed by a `nix-env -i --max-jobs <non-zero>`.
NOTE3: actually why not simply adding the output of `nix-build` to the `PATH` instead of installing it?
=> Use cache.nixos.org

niv-updater
r.duckduckgo.com seems to stopped doing redirects. We need them to
prevent github from backlinking into issues.
This change switches to using togithub.com, the same service used by the
renovatebot.
Closes #49
=> Fix: use togithub.com redirects instead of duckduckgo

niv-updater
This might actually fail (depending on which commands you use) because starting with 2.4 the two-word commands became guarded by an option. So this should be tested before releasing :-)
=> Bump `nix` to 2.11.1

niv-updater
Base branch should not include `refs/heads/`
=> Remove refs/heads/ from the base branch name

README.adoc, niv-updater
Self hosted runners are running with dynamic users so nix profile is not
accessible. Use nix-shell to have the required dependencies in PATH instead.
=> Enable action using self hosted runners

action.yml
Node 16 has reached its end of life
More details here: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> Use nodejs 20
